[package]
name = "rabbitmq"
version = "0.1.0"
authors = ["Maciej Ładoś <maciej@lados.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amiquip = "0.4"
